#!/bin/bash

# ./stopCDN -p 20030 -o cs5700cdnorigin.ccs.neu.edu:8080 -n cs5700cdn.example.com -u promised_lan -i ~/.ssh/id_ed25519.pub

# Define the options and their arguments
while getopts ":p:o:n:u:i:" opt; do
  case $opt in
    p)
      port="$OPTARG"
      ;;
    o)
      origin="$OPTARG"
      ;;
    n)
      name="$OPTARG"
      ;;
    u)
      username="$OPTARG"
      ;;
    i)
      keyfile="$OPTARG"
      ;;
    \?) # invalid option is encountered
      # an error message is printed and the script exits with a non-zero status code
      echo "Invalid option: -$OPTARG" >&2
      echo 'Run with: "./stopCDN -p <port number> -o <origin server name> -n <CDN domain name> -u <username> -i <path to public key>"'
      exit 1
      ;;
    :) # When an option requires an argument but none is provided
      # an error message is printed and the script exits with a non-zero status code
      echo "Option -$OPTARG requires an argument." >&2
      echo 'Run with: "./stopCDN -p <port number> -o <origin server name> -n <CDN domain name> -u <username> -i <path to public key>"'
      exit 1
      ;;
  esac
done

# Process the options and their arguments
echo "port = $port"
echo "origin = $origin"
echo "name = $name"
echo "username = $username"
echo "keyfile = $keyfile"

# shutdown DNS
ssh -i "$keyfile" "$username@cdn-dns.5700.network" "kill \$(lsof -i :$port | awk 'NR==2{print \$2}' | cut -d' ' -f1)" &

# shutdown HTTP
# (and remove files, NOTE: ALL CACHE FILES WILL BE DELETED (AND RELOAD TAKES ~5-10 min)...
# swap the commented/uncommented lines to stop the file removal)

#ssh -i $keyfile $username@cdn-http1.5700.network 'killall -9 python3' 2>/dev/null&
ssh -i $keyfile $username@cdn-http1.5700.network 'killall -9 python3 && rm -f *.gz httpserver urls.txt prepare_http_cache.py' 2>/dev/null&

#ssh -i $keyfile $username@cdn-http2.5700.network 'killall -9 python3' 2>/dev/null&
ssh -i $keyfile $username@cdn-http2.5700.network 'killall -9 python3 && rm -f *.gz httpserver urls.txt prepare_http_cache.py' 2>/dev/null&

#ssh -i $keyfile $username@cdn-http3.5700.network 'killall -9 python3' 2>/dev/null&
ssh -i $keyfile $username@cdn-http3.5700.network 'killall -9 python3 && rm -f *.gz httpserver urls.txt prepare_http_cache.py' 2>/dev/null&

#ssh -i $keyfile $username@cdn-http4.5700.network 'killall -9 python3' 2>/dev/null&
ssh -i $keyfile $username@cdn-http4.5700.network 'killall -9 python3 && rm -f *.gz httpserver urls.txt prepare_http_cache.py' 2>/dev/null&

#ssh -i $keyfile $username@cdn-http5.5700.network 'killall -9 python3' 2>/dev/null&
ssh -i $keyfile $username@cdn-http5.5700.network 'killall -9 python3 && rm -f *.gz httpserver urls.txt prepare_http_cache.py' 2>/dev/null&

#ssh -i $keyfile $username@cdn-http6.5700.network 'killall -9 python3' 2>/dev/null&
ssh -i $keyfile $username@cdn-http6.5700.network 'killall -9 python3 && rm -f *.gz httpserver urls.txt prepare_http_cache.py' 2>/dev/null&

#ssh -i $keyfile $username@cdn-http7.5700.network 'killall -9 python3' 2>/dev/null&
ssh -i $keyfile $username@cdn-http7.5700.network 'killall -9 python3 && rm -f *.gz httpserver urls.txt prepare_http_cache.py' 2>/dev/null&

disown
exit
